# Generated by Django 5.1.1 on 2025-10-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('D', 'Deposito'), ('S', 'Saque'), ('T', 'Transferencia'), ('P', 'PIX')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chave', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatoria')], max_length=10, verbose_name='Tipo de Chave')),
                ('chave', models.CharField(max_length=200, unique=True, verbose_name='Chave PIX')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criacao')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to='contas.conta', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Chave PIX',
                'verbose_name_plural': 'Chaves PIX',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
